# Generated by Django 4.2.7 on 2023-11-08 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_from",
                    models.CharField(
                        max_length=200, verbose_name="Адрес подачи"
                    ),
                ),
                (
                    "address_to",
                    models.CharField(
                        max_length=200, verbose_name="Адрес прибытия"
                    ),
                ),
                (
                    "addition",
                    models.CharField(
                        max_length=300, verbose_name="Комментарий"
                    ),
                ),
                ("delay", models.BooleanField(verbose_name="Задержка")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Эконом", "Эконом"),
                            ("Экспресс", "Экспресс"),
                            ("Манипулятор", "Манипулятор"),
                        ],
                        max_length=50,
                        verbose_name="Название тарифа",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Описание тарифа"
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Цена тарифа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф",
                "verbose_name_plural": "Тарифы",
            },
        ),
        migrations.CreateModel(
            name="TowTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(verbose_name="Статус эвакуатора."),
                ),
                (
                    "driver",
                    models.CharField(
                        help_text="Укажите водителя",
                        max_length=255,
                        verbose_name="Водитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эвакуатор",
                "verbose_name_plural": "Эвакуаторы",
            },
        ),
        migrations.CreateModel(
            name="PriceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("Легковой", "Легковой"),
                            ("Грузовой", "Грузовой"),
                            ("Мотоцикл", "Мотоцикл"),
                            ("Спецтехника", "Спецтехника"),
                        ],
                        max_length=30,
                        verbose_name="Тип машины",
                    ),
                ),
                (
                    "wheel_lock",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                        verbose_name="Заблокированные колеса",
                    ),
                ),
                ("towin", models.BooleanField(verbose_name="Кюветные работы")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="towin.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        max_length=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="towin.tariff",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказы и Цены",
                "verbose_name_plural": "Заказы и цены",
                "ordering": ("order",),
            },
        ),
        migrations.AddField(
            model_name="order",
            name="tow_truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="towin.towtruck",
                verbose_name="Эвакуатор",
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=400, verbose_name="Комментарий"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="towin.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddConstraint(
            model_name="priceorder",
            constraint=models.UniqueConstraint(
                fields=("order",), name="unique_order"
            ),
        ),
    ]
